import type { Property } from './types';

export const properties: Property[] = [
  {
    id: '1',
    title: 'Luxury 3-Bedroom Apartment in Kilimani',
    description: 'A stunning and spacious 3-bedroom apartment located in the heart of Kilimani. Features modern finishes, a large balcony with city views, and access to a swimming pool and gym. Perfect for families or professionals looking for comfort and convenience.',
    price: 150000,
    location: 'Kilimani, Nairobi',
    city: 'Nairobi',
    bedrooms: 3,
    bathrooms: 4,
    area: 2200,
    type: 'Apartment',
    amenities: ['Swimming Pool', 'Gym', '24/7 Security', 'Backup Generator', 'High-speed Lifts', 'Parking'],
    images: ['property_1_1', 'property_1_2', 'property_1_3'],
    agent: { name: 'Jane Doe', avatar: 'agent_1' },
    featured: true,
    latitude: -1.2998,
    longitude: 36.7820,
    status: 'For Rent',
  },
  {
    id: '2',
    title: 'Charming 4-Bedroom House in Karen',
    description: 'Experience tranquility in this beautiful 4-bedroom house in Karen. Set on a half-acre of lush gardens, this home offers a serene environment, a spacious living area with a fireplace, and a modern kitchen. Ideal for those who value privacy and nature.',
    price: 350000,
    location: 'Karen, Nairobi',
    city: 'Nairobi',
    bedrooms: 4,
    bathrooms: 4,
    area: 4500,
    type: 'House',
    amenities: ['Garden', 'Fireplace', 'DSQ', 'Pet Friendly', 'Electric Fence', 'Ample Parking'],
    images: ['property_2_1', 'property_2_2', 'property_2_3'],
    agent: { name: 'John Smith', avatar: 'agent_2' },
    featured: true,
    latitude: -1.3218,
    longitude: 36.7061,
    status: 'For Rent',
  },
  {
    id: '3',
    title: 'Modern 2-Bedroom with City Views',
    description: 'A chic 2-bedroom apartment in Westlands offering breathtaking views of the Nairobi skyline. This unit is perfect for young professionals, featuring an open-plan living space, stylish interiors, and proximity to major shopping malls and offices.',
    price: 120000,
    location: 'Westlands, Nairobi',
    city: 'Nairobi',
    bedrooms: 2,
    bathrooms: 2,
    area: 1500,
    type: 'Apartment',
    amenities: ['Rooftop Terrace', 'Gym', 'Borehole', 'Solar Water Heating', 'CCTV'],
    images: ['property_3_1'],
    agent: { name: 'Jane Doe', avatar: 'agent_1' },
    featured: true,
    latitude: -1.266,
    longitude: 36.802,
    status: 'For Rent',
  },
  {
    id: '4',
    title: 'Cozy Townhouse in Lavington',
    description: 'A lovely 4-bedroom townhouse in a gated community in Lavington. This home provides a safe and quiet environment for a family, with a private garden, a community pool, and easy access to prestigious schools.',
    price: 280000,
    location: 'Lavington, Nairobi',
    city: 'Nairobi',
    bedrooms: 4,
    bathrooms: 5,
    area: 3500,
    type: 'Townhouse',
    amenities: ['Gated Community', 'Swimming Pool', 'Private Garden', 'Clubhouse'],
    images: ['property_4_1'],
    agent: { name: 'John Smith', avatar: 'agent_2' },
    featured: true,
    latitude: -1.285,
    longitude: 36.77,
    status: 'Rented',
  },
  {
    id: '5',
    title: 'Executive Condo in Nyali',
    description: 'Live by the coast in this luxurious 3-bedroom condo in Nyali, Mombasa. Enjoy sea views, a private beach access, and resort-style amenities. The perfect getaway or permanent residence for those who love the ocean.',
    price: 200000,
    location: 'Nyali, Mombasa',
    city: 'Mombasa',
    bedrooms: 3,
    bathrooms: 3,
    area: 2500,
    type: 'Condo',
    amenities: ['Beach Access', 'Sea View', 'Infinity Pool', 'A/C', 'Fully Furnished'],
    images: ['property_5_1'],
    agent: { name: 'Jane Doe', avatar: 'agent_1' },
    featured: true,
    latitude: -4.032,
    longitude: 39.704,
    status: 'For Rent',
  },
   {
    id: '6',
    title: 'Penthouse Apartment with Rooftop Pool',
    description: 'An exclusive penthouse in Kileleshwa with a private rooftop pool and entertainment area. This 4-bedroom duplex offers unparalleled luxury, panoramic views, and high-end finishes throughout.',
    price: 500000,
    location: 'Kileleshwa, Nairobi',
    city: 'Nairobi',
    bedrooms: 4,
    bathrooms: 5,
    area: 5000,
    type: 'Apartment',
    amenities: ['Rooftop Pool', 'Private Cinema', 'Sauna', 'Jacuzzi', 'Smart Home System'],
    images: ['property_6_1'],
    agent: { name: 'John Smith', avatar: 'agent_2' },
    featured: true,
    latitude: -1.280,
    longitude: 36.789,
    status: 'For Rent',
  },
];
